# Generated by Django 4.2.6 on 2023-10-31 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dname', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Dob', models.DateField(blank=True, null=True)),
                ('Age', models.IntegerField()),
                ('Gender', models.CharField(max_length=20)),
                ('Phone_number', models.IntegerField()),
                ('Mailid', models.EmailField(max_length=254)),
                ('Address', models.TextField()),
                ('Account_type', models.CharField(max_length=100)),
                ('Materials', models.CharField(max_length=100)),
                ('Branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bankapp.branch')),
                ('District', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bankapp.district')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='Disname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bankapp.district'),
        ),
    ]
