# Generated by Django 4.2.6 on 2023-10-31 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_alter_customer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Account_type',
            field=models.CharField(choices=[('Current Account', 'Current Account'), ('Savings', 'Savings'), ('RD Account', 'RD Account'), ('FD Account', 'FD Account'), ('NRI Account', 'NRI Account')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other')], max_length=20),
        ),
    ]
