# Generated by Django 4.2.6 on 2023-11-01 07:37

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_alter_customer_account_type_alter_customer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Materials',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Debit Card', 'Debit Card'), ('Credit Card', 'Credit Card'), ('Cheque Book', 'Cheque Book')], max_length=100),
        ),
    ]
