# Generated by Django 4.2.6 on 2023-11-02 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0004_alter_customer_materials'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='Disname',
            new_name='District',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='Bname',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='district',
            old_name='Dname',
            new_name='Name',
        ),
    ]
