# Generated by Django 4.2.6 on 2023-11-04 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0005_rename_disname_branch_district_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='Dob',
            new_name='Birthdate',
        ),
    ]
