# Generated by Django 4.2.6 on 2023-11-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0006_rename_dob_customer_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Birthdate',
            field=models.DateField(),
        ),
    ]
