# Generated by Django 4.2.6 on 2023-11-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0007_alter_customer_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Birthdate',
        ),
        migrations.AddField(
            model_name='customer',
            name='Date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
